### ISSUE TITLE
Not found

### ISSUE THREAD

**Issue by dicristomanuel** [mesilliac/pulse-simple#3]
When running `go build` from the main directory i get this error message:
```
Package libpulse-simple was not found in the pkg-config search path.
Perhaps you should add the directory containing `libpulse-simple.pc'
to the PKG_CONFIG_PATH environment variable
```

Any suggestion?

**Comment by mesilliac** [comment]
Hi there - yep i know what this is. Go just needs to be able to find the pulseaudio C header files somewhere. On Ubuntu they can be installed with `sudo apt install libpulse-dev`, and on other distros there should be a similar package. I'll add this to the readme as well.

**Comment by dicristomanuel** [comment]
Thank you!
